apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-app
spec:
  selector:
    matchLabels:
      app: greet-app
  replicas: 1
  template:
    metadata:
      labels:
        app: greet-app
    spec:
      containers:
        - name: greet-app-container
          image: ram1uj/greet-app:latest
          ports:
              - containerPort: 8080
          env:
            - name: MESSAGE
              valueFrom:
                secretKeyRef:
                  name: greet-app-secret
                  key: MESSAGE

