apiVersion: v1
kind: Service
metadata:
  name: part-inventory-service
spec:
  selector:
    app: part-inventory-service
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
