apiVersion: v1
kind: Service
metadata:
  name: part-inventory-service
  namespace: default
spec:
  selector:
    app: part-inventory
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
  type: NodePort
