apiVersion: v1
kind: Service
metadata:
  name: part-order-service
  namespace: default
spec:
  selector:
    app: part-order
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
  type: NodePort
