apiVersion: apps/v1
kind: Deployment
metadata:
  name: part-inventory-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: part-inventory

  template:
    metadata:
      labels:
        app: part-inventory
    spec:
      containers:
        - name: part-inventory
          image: ram1uj/part-inventory-service:latest
          ports:
            - containerPort: 8080
