apiVersion: apps/v1
kind: Deployment
metadata:
  name: part-order-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: part-order

  template:
    metadata:
      labels:
        app: part-order
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "backend"
          effect: "NoExecute"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - spot
              weight: 10

      containers:
        - name: part-order
          image: ram1uj/part-order-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
#            - name: MYSQL_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: part-inventory-config
#                  key: MYSQL_HOST
#            - name: MYSQL_PORT
#              valueFrom:
#                configMapKeyRef:
#                  name: part-inventory-config
#                  key: MYSQL_PORT
#            - name: MYSQL_DATABASE
#              valueFrom:
#                configMapKeyRef:
#                  name: part-inventory-config
#                  key: MYSQL_DATABASE
#            - name: MYSQL_USER
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-secret
#                  key: MYSQL_USER
#            - name: MYSQL_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-secret
#                  key: MYSQL_PASSWORD
            - name: INVENTORY_SERVICE_URL
              value: "http://part-inventory-service"
          ports:
            - containerPort: 8080
