apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-app
spec:
  selector:
    matchLabels:
      app: ecom-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
        - name: product-app-container
          image: ram1uj/product-app:latest
          ports:
            - containerPort: 8080
        - name: cart-service
          image: ram1uj/cart-app:latest
#          command:
#            - "--server.port=80"
          env:
            - name: SERVER_PORT
              value: "80"
          ports:
            - containerPort: 80
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"