apiVersion: v1
kind: Service
metadata:
  name: ecom-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      name: http
    - port: 8081
      targetPort: 80
      nodePort: 30081
      name: cart-http

  selector:
    app: ecom-app