apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: easy-recipes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easy-recipes
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: 60
