apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-role-binding
#  namespace: dev
subjects:
  - kind: ServiceAccount
    name: qa-user

roleRef:
  kind: Role
  name: qa-role
  apiGroup: rbac.authorization.k8s.io