apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-role
#  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
